# Generated by Django 5.0.6 on 2024-07-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('Quiz', 'Quiz'), ('Teacher Assessment', 'Teacher Assessment'), ('Mid Semester Exam', 'Mid Semester Exam'), ('End Semester Exam', 'End Semester Exam')], max_length=50)),
                ('mark', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.assign')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.student')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
                'unique_together': {('assign', 'student', 'test_name')},
            },
        ),
    ]
