# Generated by Django 5.0.6 on 2024-07-02 20:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='program',
        ),
        migrations.AddField(
            model_name='class',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.branch'),
        ),
        migrations.AddField(
            model_name='class',
            name='degree',
            field=models.CharField(choices=[('Bachelor of Technology', 'Bachelor of Technology'), ('Master of Technology', 'Master of Technology'), ('Doctor of Philosophy', 'Doctor of Philosophy')], default='Bachelor of Technology'),
        ),
        migrations.AddField(
            model_name='class',
            name='sem',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
