# Generated by Django 5.0.6 on 2024-06-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_dept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
