# Generated by Django 5.0.6 on 2024-07-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
