# Generated by Django 5.0.6 on 2024-07-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_class_program_class_branch_class_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.branch'),
        ),
        migrations.AlterField(
            model_name='class',
            name='degree',
            field=models.CharField(choices=[('Bachelor of Technology', 'Bachelor of Technology'), ('Master of Technology', 'Master of Technology'), ('Doctor of Philosophy', 'Doctor of Philosophy')]),
        ),
    ]
