# Generated by Django 5.0.6 on 2024-06-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_dept_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('name', models.CharField(choices=[('Bacholer of Technology', 'B. Tech'), ('Master of Technology', 'M. Tech'), ('Doctor of Philosophy', 'PHD')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='dept',
            name='id',
            field=models.CharField(max_length=10, primary_key='True', serialize=False),
        ),
    ]
