# Generated by Django 5.0.6 on 2024-06-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_degree_alter_dept_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('degree', models.CharField(blank='False', choices=[('Bachelor of Technology', 'Bachelor of Technology'), ('Master of Technology', 'Master of Technology'), ('Doctor of Philosophy', 'Doctor of Philosophy')], null='False')),
                ('branch', models.CharField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.dept')),
            ],
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
