# Generated by Django 5.0.6 on 2024-07-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='Include Country Code (+91)', max_length=13, unique=True),
        ),
    ]
