# Generated by Django 5.0.6 on 2024-06-24 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_program_delete_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(choices=[('Bachelor of Technology', 'Bachelor of Technology'), ('Master of Technology', 'Master of Technology'), ('Doctor of Philosophy', 'Doctor of Philosophy')]),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.branch'),
        ),
    ]
