# Generated by Django 5.0.6 on 2024-07-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_student_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
