# Generated by Django 5.0.6 on 2024-06-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_branch_alter_program_degree_alter_program_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='dept',
        ),
        migrations.AddField(
            model_name='branch',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
        ),
    ]
