# Generated by Django 5.0.6 on 2024-06-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_branch_options_remove_program_dept_branch_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.dept'),
        ),
    ]
