# Generated by Django 5.0.6 on 2024-07-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_faculty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markclass',
            name='test_name',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Faculty Assessment', 'Faculty Assessment'), ('Mid Semester Exam', 'Mid Semester Exam'), ('End Semester Exam', 'End Semester Exam')], max_length=50),
        ),
    ]
