# Generated by Django 5.0.6 on 2024-07-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_markclass_test_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('course', 'class_id')},
        ),
    ]
