# Generated by Django 5.0.6 on 2024-06-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_course_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('batch', models.CharField(help_text='E.g 2021-25')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.program')),
            ],
        ),
    ]
