# Generated by Django 5.0.6 on 2024-06-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
