# Generated by Django 5.0.6 on 2024-07-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_attendancerange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceTotal',
            new_name='StudentCourse',
        ),
    ]
