# Generated by Django 5.0.6 on 2024-07-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_rename_attendancetotal_studentcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='markclass',
            unique_together={('assign', 'test_name')},
        ),
    ]
