# Generated by Django 5.0.6 on 2024-06-26 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_alter_class_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('DOB', models.DateField(default='2000-01-01')),
                ('phone_number', models.CharField(blank=True, help_text='Include Country Code (+91)', max_length=13, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('class_id', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, to='info.class', verbose_name='Class')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
