# Generated by Django 5.0.6 on 2024-06-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='short_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
