# Generated by Django 5.0.6 on 2024-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_alter_markclass_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(help_text='Include Country Code (+91)', max_length=13, null=True, unique=True),
        ),
    ]
