# Generated by Django 5.0.6 on 2024-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_branch_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
    ]
