# Generated by Django 5.0.6 on 2024-06-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.CASCADE, to='info.class', verbose_name='Class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.faculty')),
            ],
            options={
                'unique_together': {('course', 'class_id', 'faculty')},
            },
        ),
    ]
