# Generated by Django 5.0.6 on 2024-06-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='id',
        ),
    ]
