# Generated by Django 5.0.6 on 2024-06-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_alter_faculty_options_alter_attendance_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assigntime',
            unique_together={('assign', 'day', 'period')},
        ),
    ]
