# Generated by Django 5.0.6 on 2024-06-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_assigntime_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assigntime',
            unique_together=set(),
        ),
    ]
